%% Adaptive Visual Servoing: Immersion and Invariance (I&I) Controller
% Reproduction of: Astolfi, Hsu, Netto, Ortega (2002)
% "Two Solutions to the Adaptive Visual Servoing Problem"
% IEEE Transactions on Robotics and Automation, Vol.18, No.3, June 2002
%
% System model: y_dot = a * exp(J*theta) * u   (Eq. 2)
% PI Controller: Eqs. (5)-(7), Proposition 1

clear; clc; close all;

%% ====== Robot & Camera Parameters ======
L1 = 0.8;       % Link 1 length [m]
L2 = 0.5;       % Link 2 length [m]
O1 = -0.666;    % Base offset x [m]  (same as [7] in paper)
O2 = -0.333;    % Base offset y [m]

theta_true = 1.0;   % True camera orientation [rad] (extreme misorientation)
a_true     = 0.7;   % True camera scale factor
episilon   = 0.5;     

%% ====== Simulation Settings ======
t_start = 0;
t_end   = 80;
dt      = 0.01;
t       = t_start:dt:t_end;
N       = length(t);

%% ====== Reference Trajectory (Tracking case) ======
% Generated by first-order filter: y_dot_star = -lambda*y_star + r
% with wr = 0.07 (faster reference, more demanding)
lambda = 1;
wr     = 0.07;
a1 = 0.04; a2 = 0.04; d = 0.04; c = 0.1; psi = 1;

% Pre-compute reference signals
r1 = a1*sin(wr*t) + c + d*sin(1.5*wr*t);
r2 = a2*sin(wr*t + psi) + c + d*sin(1.5*wr*t + psi);

% Analytical ṙ
r1_dot = a1*wr*cos(wr*t) + 1.5*d*wr*cos(1.5*wr*t);
r2_dot = a2*wr*cos(wr*t + psi) + 1.5*d*wr*cos(1.5*wr*t + psi);

% Integrate reference trajectory using Euler method
y_star     = zeros(2, N);
y_star_dot = zeros(2, N);
y_star_ddot= zeros(2, N);
y_star(:,1) = [0.3; 0.3];  % initial reference

for k = 1:N-1
    y_star_dot(:,k) = -lambda*y_star(:,k) + [r1(k); r2(k)];
    y_star(:,k+1) = y_star(:,k) + dt * y_star_dot(:,k);
end
y_star_dot(:,N) = -lambda*y_star(:,N) + [r1(N); r2(N)];

% Compute reference acceleration by finite differences
% ÿ* = -λẏ* + ṙ  (analytical, no finite differences needed)
for k = 1:N
    y_star_ddot(:,k) = -lambda*y_star_dot(:,k) + [r1_dot(k); r2_dot(k)];
end

%% ====== Initial Conditions ======
q0 = [1.3; -1.3];    % Initial joint angles [rad]
theta_hat0 = 0;       % Initial estimate of camera orientation

% Compute initial end-effector position in image space
k0 = forward_kinematics(q0, L1, L2, O1, O2);
y0 = a_true * rot_matrix(theta_true) * k0;  % simplified: vartheta1=0, vartheta2=0

%% ====== Storage ======
y       = zeros(2, N);
y_tilde = zeros(2, N);
theta_hat_hist = zeros(1, N);
u_hist  = zeros(2, N);
s_hist  = zeros(2, N);
q_hist  = zeros(2, N);

y(:,1)         = y0;
theta_hat_hist(1) = theta_hat0;
q_hist(:,1)    = q0;

%% ====== Euler Integration of Closed-Loop System ======
theta_hat = theta_hat0;
q = q0;
y_curr = y0;

fprintf('Running I&I Adaptive Visual Servoing Simulation...\n');

for k = 1:N-1
    ys  = y_star(:,k);
    ysd = y_star_dot(:,k);
    ysdd = y_star_ddot(:,k);

    % Tracking error
    y_tilde_k = y_curr - ys;

    % Sliding variable s = y_tilde - y_star_dot  (Eq. 7)
    s = y_tilde_k - 1/episilon * ysd;

    % caluculate z
    beta = 0.5 * norm(y_tilde_k)^2 - 1/episilon*y_tilde_k'*ysd;
    z = theta_hat + beta;

    % PI Control law 
    u = -z * cos(z) * s;

    % Parameter update law (Eq. 6): theta_hat_dot = s' * (y_tilde + y_star_dot)
    % Note: in paper eq.(6), argument is (y_tilde + y_star) — here y_star means y_star_dot
    % Correcting per paper: dot_theta_hat = s^T * (tilde_y + dot_y_star)
    theta_hat_dot = s' * ysd +  1/episilon*y_tilde_k'*ysdd + episilon*norm(s)^2;

    % Compute robot Jacobian and input u_joint
    J_rob = robot_jacobian(q, L1, L2);
    tau = J_rob \ u;   % joint velocity = J^{-1} * u (robot integrator model)

    % System dynamics: y_dot = a * exp(J*theta) * u  (Eq. 2)
    eJtheta = rot_matrix(theta_true);
    y_dot = a_true * eJtheta * u;

    % Euler update
    y_curr    = y_curr + dt * y_dot;
    theta_hat = theta_hat + dt * theta_hat_dot;
    q         = q + dt * tau;

    % Store
    y(:,k+1)              = y_curr;
    y_tilde(:,k+1)        = y_curr - y_star(:,k+1);
    theta_hat_hist(k+1)   = theta_hat;
    u_hist(:,k)           = u;
    s_hist(:,k)           = s;
    q_hist(:,k+1)         = q;
end
% Last step
s_hist(:,N) = s_hist(:,N-1);
u_hist(:,N) = u_hist(:,N-1);
y_tilde(:,1) = y(:,1) - y_star(:,1);

fprintf('Simulation complete.\n');

%% ====== Compute Control Torques (for display) ======
% Actual joint torques via Jacobian transpose (kinematic model)
tau_hist = zeros(2, N);
for k = 1:N
    J_rob = robot_jacobian(q_hist(:,k), L1, L2);
    tau_hist(:,k) = J_rob \ u_hist(:,k);
end
torque_norm = sqrt(tau_hist(1,:).^2 + tau_hist(2,:).^2);

%% ====== Reference signal for set-point test (additional) ======
% Quick set-point convergence check (y_star = [0.1; 0.1])
fprintf('\n--- Set-Point Control Results ---\n');
% Find time to reach within 4%% of final value
target = [0.1; 0.1];
err_norm = sqrt(sum((y - target).^2, 1));
idx_conv = find(err_norm < 0.04*norm(target), 1, 'first');
if ~isempty(idx_conv)
    fprintf('Convergence within 4%%%% of setpoint at t = %.1f s\n', t(idx_conv));
else
    fprintf('Did not converge within 4%%%% during tracking simulation\n');
end
fprintf('Max control torque: %.3f Nm\n', max(torque_norm));

%% ====== Plotting ======
fig = figure('Name','I&I Adaptive Visual Servoing','Position',[100 100 1200 900]);
set(fig,'Color','white');

% --- Plot 1: y1 tracking ---
subplot(2,2,1);
plot(t, y(1,:), 'b-', 'LineWidth', 1.5); hold on;
plot(t, y_star(1,:), 'r--', 'LineWidth', 1.5);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('y_1', 'FontSize', 12);
title('Image Output y_1 vs Reference y_{1*}', 'FontSize', 12);
legend('y_1(t)', 'y_{1*}(t)', 'Location', 'best');
grid on; xlim([0 t_end]);

% --- Plot 2: y2 tracking ---
subplot(2,2,2);
plot(t, y(2,:), 'b-', 'LineWidth', 1.5); hold on;
plot(t, y_star(2,:), 'r--', 'LineWidth', 1.5);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('y_2', 'FontSize', 12);
title('Image Output y_2 vs Reference y_{2*}', 'FontSize', 12);
legend('y_2(t)', 'y_{2*}(t)', 'Location', 'best');
grid on; xlim([0 t_end]);

% --- Plot 3: Tracking error norm ---
subplot(2,2,3);
err = sqrt(y_tilde(1,:).^2 + y_tilde(2,:).^2);
plot(t, err, 'm-', 'LineWidth', 1.5);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('||\\tilde{y}||', 'FontSize', 12);
title('Tracking Error Norm ||\tilde{y}||', 'FontSize', 12);
grid on; xlim([0 t_end]);

% --- Plot 4: Camera orientation estimate ---
subplot(2,2,4);
plot(t, theta_hat_hist, 'g-', 'LineWidth', 1.5); hold on;
plot(t, theta_true*ones(1,N), 'k--', 'LineWidth', 1.2);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('\hat{\theta} [rad]', 'FontSize', 12);
title('Camera Orientation Estimate \hat{\theta}', 'FontSize', 12);
legend('\hat{\theta}(t)', '\theta_{true} = 1 rad', 'Location', 'best');
grid on; xlim([0 t_end]);

sgtitle('I\&I Adaptive Visual Servoing Controller (Astolfi et al. 2002)', ...
    'FontSize', 14, 'FontWeight', 'bold');

% Save figure
saveas(fig, '/mnt/user-data/outputs/II_controller_tracking.png');
fprintf('Figure saved.\n');

%% ====== Second Figure: Control Effort & Sliding Variable ======
fig2 = figure('Name','Control Effort','Position',[100 100 1000 500]);
set(fig2,'Color','white');

subplot(1,2,1);
plot(t, torque_norm, 'b-', 'LineWidth', 1.5);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('||u_{joint}|| [Nm]', 'FontSize', 12);
title('Control Torque Norm', 'FontSize', 12);
grid on; xlim([0 t_end]);
yline(1.1, 'r--', 'Max = 1.1 Nm', 'FontSize', 10);

subplot(1,2,2);
s_norm = sqrt(s_hist(1,:).^2 + s_hist(2,:).^2);
plot(t, s_norm, 'r-', 'LineWidth', 1.5);
xlabel('Time (sec)', 'FontSize', 11);
ylabel('||s||', 'FontSize', 12);
title('Sliding Variable ||s||', 'FontSize', 12);
grid on; xlim([0 t_end]);

sgtitle('I\&I Controller: Control Effort & Sliding Variable', ...
    'FontSize', 13, 'FontWeight', 'bold');

saveas(fig2, '/mnt/user-data/outputs/II_controller_effort.png');
fprintf('Control effort figure saved.\n');

%% ====== Helper Functions ======

function k = forward_kinematics(q, L1, L2, O1, O2)
    % End-effector Cartesian position
    x1 = L1*cos(q(1)) + L2*cos(q(1)+q(2)) + O1;
    x2 = L1*sin(q(1)) + L2*sin(q(1)+q(2)) + O2;
    k = [x1; x2];
end

function R = rot_matrix(angle)
    % 2D rotation matrix exp(J*angle) where J = [0 -1; 1 0]
    R = [cos(angle), -sin(angle);
         sin(angle),  cos(angle)];
end

function Jac = robot_jacobian(q, L1, L2)
    % Analytic Jacobian of end-effector w.r.t. joint angles
    Jac = [-L1*sin(q(1)) - L2*sin(q(1)+q(2)),  -L2*sin(q(1)+q(2));
            L1*cos(q(1)) + L2*cos(q(1)+q(2)),   L2*cos(q(1)+q(2))];
end